name: Deploy Express.js to EC2

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} echo "SSH connection successful"

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            if [ ! -d "/home/${{ secrets.AWS_EC2_USER }}/app" ]; then
              git clone https://github.com/yourusername/yourrepo.git /home/${{ secrets.AWS_EC2_USER }}/app
            fi

            cd /home/${{ secrets.AWS_EC2_USER }}/app

            git pull origin main

            npm install

            pm2 restart app || pm2 start npm --name "app" -- start

            pm2 save
          EOF
