name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Only run on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      JWT_SECRET: ${{ secrets.JWT_SECRET }}  # Ensure you have this secret set up in your repo

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust to the Node.js version you are using

    - name: Install Dependencies
      run: npm ci  # Use npm ci for a clean install from package-lock.json

    - name: Run Tests
      run: npm test -- --coverage  # Run all your tests including JWT logic tests

    - name: List Coverage Directory
      run: ls -al ./coverage  # Verify that the coverage report was generated

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage/lcov.info  # Ensure this points to your coverage report
        token: ${{ secrets.CODECOV_TOKEN }}  # Set this token in GitHub secrets

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0  # Adjust if using a different version

    - name: Initialize Terraform
      run: terraform init
      working-directory: infra/terraform  # Path to Terraform files

    - name: Terraform Refresh
      run: terraform refresh
      working-directory: infra/terraform  # Path to Terraform files

    - name: Terraform Destroy Existing Instance
      working-directory: infra/terraform
      run: terraform destroy -auto-approve -target=aws_instance.app_server

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan
      working-directory: infra/terraform  # Path to Terraform files

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
      working-directory: infra/terraform  # Path to Terraform files
