name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up SSH
      # Updated to the assumed latest stable version. 
      # Please verify the latest version on the GitHub Marketplace or its repository
      uses: webfactory/ssh-agent@v0.6.0  # Assuming v0.6.0, replace with the latest version

      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Copy files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r . ec2-user@your-ec2-public-dns:/home/ec2-user/app

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-public-dns << 'EOF'
          cd /home/ec2-user/app
          docker build -t my-nginx-image .
          docker run -d -p 80:80 my-nginx-image
        EOF
