name: Deploy Express.js to EC2

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            # Navigate to the project directory or clone the repository if not already done
            if [ ! -d "/home/${{ secrets.AWS_EC2_USER }}/app" ]; then
              git clone https://github.com/yourusername/yourrepo.git /home/${{ secrets.AWS_EC2_USER }}/app
            fi

            cd /home/${{ secrets.AWS_EC2_USER }}/app

            # Pull the latest changes
            git pull origin main

            # Install dependencies
            npm install

            # Restart the application using PM2
            pm2 restart app || pm2 start npm --name "app" -- start

            # Save the PM2 process list to start on reboot
            pm2 save
          EOF
